In [1]:
import cv2
import numpy as np
import torch

# 图像的输入和保存


In [3]:
pic = cv2.imread(r"image\lenacolor.png")

In [3]:
print(pic.shape)

(512, 512, 3)


In [4]:
type(pic)

numpy.ndarray

In [5]:
pic.shape

(512, 512, 3)

In [9]:
# cv2.namedWindow("test",0)
cv2.imshow("cat",pic)
ret = cv2.waitKey(0)
print(ret)
cv2.waitKey(0)

97


98

In [7]:
cv2.imwrite("mn.jpg",pic)

True

# 图像基本处理

In [29]:
pic[100,100] 

array([255, 255, 255], dtype=uint8)

In [11]:
pic[100,100] = [255,255,255]

In [12]:
pic[100,100] 

array([255, 255, 255], dtype=uint8)

In [24]:
pic[100:151:,100:151:]=[255,255,255]



In [25]:
cv2.imshow("cat",pic)
ret = cv2.waitKey(0)

In [26]:
face = pic[220:400,250:350]

In [27]:
cv2.imshow("cat",face)
ret = cv2.waitKey(0)

In [40]:
trump = cv2.imread(r'image\trump_face.png')
pic[250:331,332:444] = trump
cv2.imshow("cat",trump)
ret = cv2.waitKey(0)

ValueError: could not broadcast input array from shape (100,113,3) into shape (81,112,3)

In [52]:
trump = cv2.imread(r'image\trump_face.png')

pic[250:350,240:353] = trump

In [53]:
cv2.imshow("cat",pic)
ret = cv2.waitKey(0)

In [5]:
b,g,r = cv2.split(pic)

In [55]:
b


array([[125, 125, 133, ..., 122, 110,  90],
       [125, 125, 133, ..., 122, 110,  90],
       [125, 125, 133, ..., 122, 110,  90],
       ...,
       [ 60,  60,  58, ...,  84,  76,  79],
       [ 57,  57,  62, ...,  79,  81,  81],
       [ 57,  57,  62, ...,  79,  81,  81]], dtype=uint8)

In [6]:
cv2.imshow('b',b)
cv2.waitKey(0)

-1

In [11]:
result = cv2.merge([r,b,g])

In [13]:
cv2.imshow('b',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

# 图像运算

In [37]:
img = cv2.imread(r"image\lena512.bmp")
boat = cv2.imread(r"image\boat.bmp")
boat = boat[0:512:,0:512:]

In [22]:
cv2.imshow('jia',resultl)
cv2.waitKey(0)

-1

In [21]:
resultl = img + img

In [23]:
res2 =  cv2.add(img,img)

In [24]:
cv2.imshow('jia',res2)
cv2.waitKey(0)

-1

In [38]:
res3 =  cv2.addWeighted(img,0.7,boat,0.3,0)

In [39]:
cv2.imshow('jia',res3)
cv2.waitKey(0)

-1

# 图像转换

In [50]:
img  = cv2.imread(r'image/lena.bmp',cv2.IMREAD_COLOR)

In [ ]:
# cv2.cvtColor(img,cv2.BGR2G)

In [49]:
cv2.imshow('jia',img)
cv2.waitKey(0)

-1

In [46]:
img.shape

(512, 512, 3)

In [47]:
img


array([[[156, 156, 156],
        [164, 164, 164],
        [156, 156, 156],
        ...,
        [164, 164, 164],
        [156, 156, 156],
        [132, 132, 132]],

       [[164, 164, 164],
        [164, 164, 164],
        [164, 164, 164],
        ...,
        [172, 172, 172],
        [156, 156, 156],
        [124, 124, 124]],

       [[164, 164, 164],
        [156, 156, 156],
        [164, 164, 164],
        ...,
        [164, 164, 164],
        [156, 156, 156],
        [132, 132, 132]],

       ...,

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 52,  52,  52],
        ...,
        [108, 108, 108],
        [100, 100, 100],
        [100, 100, 100]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 60,  60,  60],
        ...,
        [100, 100, 100],
        [108, 108, 108],
        [108, 108, 108]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 52,  52,  52],
        ...,
        [108, 108, 108],
        [100, 100, 100],
        [108, 108, 108]]

In [4]:
img  = cv2.imread(r'image/test_Hillary.jpg')

In [5]:
res1 = cv2.resize(img,None,fx =4,fy=4,interpolation = cv2.INTER_NEAREST)
res2 = cv2.resize(img,None,fx =4,fy=4,interpolation = cv2.INTER_NEAREST_EXACT)

In [7]:
cv2.imshow('jia',res2)
cv2.waitKey(0)

32

In [6]:
img = cv2.imread(r"image\lenacolor.png")

In [9]:
size = 512 *1.5
size

768.0

In [16]:
res = cv2.resize(img,(int(size),int(size)),cv2.INTER_LINEAR )#resize是修改宽高看是否xy相反

In [21]:
res2 = cv2.resize(img,None,fx =0.5,fy =0.5 ,interpolation = cv2.INTER_LINEAR)

In [22]:
cv2.imshow('jia',res)
cv2.imshow('jian',res2)

cv2.waitKey(0)

-1

In [24]:
dstx = cv2.flip(img,0)
dsty = cv2.flip(img,1)
dstz = cv2.flip(img,-2)


In [25]:
cv2.imshow('x',dstx)
cv2.imshow('y',dsty)
cv2.imshow('x,y',dstz)
cv2.imshow('yuantu',img)
cv2.waitKey(0)

-1

In [46]:
height,width = img.shape[:2]

In [62]:
srcpic  = np.array([[122,73],[317,112],[70,239]],dtype= np.float32)

In [63]:
after  = np.array([[111,345],[132,374],[171,256]],dtype = np.float32)

In [64]:
M = cv2.getAffineTransform(srcpic,after)

In [65]:
ans  = cv2.warpAffine(img,M,(height,width),borderValue = (255,255,255))

In [66]:
cv2.imshow('x',ans)
cv2.imshow('source',img)
cv2.waitKey(0)

-1