In [1]:
import cv2
import numpy as np

阈值分割

1、反二进制阈值化
2、二进制阈值化
3、

In [3]:
img = cv2.imread(r'image\cameraman.tif',cv2.IMREAD_GRAYSCALE)


In [4]:
img.shape

(256, 256)

In [6]:
thresh1,dst1 = cv2.threshold(img,100,255,cv2.THRESH_BINARY)
thresh2,dst2 = cv2.threshold(img,100,255,cv2.THRESH_BINARY_INV)
thresh3,dst3 = cv2.threshold(img,100,255,cv2.THRESH_TRUNC)
thresh4,dst4 = cv2.threshold(img,100,255,cv2.THRESH_TOZERO)
thresh5,dst5 = cv2.threshold(img,100,255,cv2.THRESH_TOZERO_INV)

In [7]:
cv2.imshow("img",img)
cv2.imshow("binary",dst1)
cv2.imshow("binary_inv",dst2)
cv2.imshow("trunc",dst3)
cv2.imshow("to 0",dst4)
cv2.imshow("to 0 inv",dst5)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
cat = cv2.imread(r'image\kitty.jpg',cv2.IMREAD_GRAYSCALE)
dog = cv2.imread(r'image\dog.jpg',cv2.IMREAD_GRAYSCALE)


In [59]:
threshCat,dstCat = cv2.threshold(cat,0,255,cv2.THRESH_BINARY_INV|cv2.THRESH_OTSU)
threshDog,dstDog = cv2.threshold(dog,0,255,cv2.THRESH_BINARY|cv2.THRESH_OTSU)

In [60]:
cv2.imshow("cat",cat)
cv2.imshow("binary_invdstCat",dstCat)

cv2.imshow("dog",dog)
cv2.imshow("binary_invdstDog",dstDog)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
threshCat,threshDog

(158.0, 174.0)

## 图像滤波

In [63]:
img =cv2.imread(r"image\lenacolor.png")

In [74]:
dst1 = cv2.blur(img,(4,4))#
dst2 = cv2.GaussianBlur(img,(3,3),sigmaX = 5)#高斯滤波
dst3 = cv2.medianBlur(img,3)#中值滤波

In [75]:
cv2.imshow("blur",dst)
cv2.imshow("src",img)

cv2.imshow("Gauss",dst2)
cv2.imshow("Medi",dst3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [76]:
img2 =cv2.imread(r"image\lenaNoise.png")

In [77]:
dst1 = cv2.blur(img2,(4,4))#
dst2 = cv2.GaussianBlur(img2,(3,3),sigmaX = 5)#高斯滤波
dst3 = cv2.medianBlur(img2,3)#中值滤波

In [78]:
cv2.imshow("blur",dst1)
cv2.imshow("src",img2)

cv2.imshow("Gauss",dst2)
cv2.imshow("Medi",dst3)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 腐蚀


In [79]:
img = cv2.imread(r'image\erode.bmp',cv2.IMREAD_GRAYSCALE)
img.shape

(600, 800)

In [97]:
kernel = np.ones((9,9),dtype = np.uint8)

In [98]:
kernel

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [105]:
dst = cv2.erode(img,kernel,iterations  = 3)#腐蚀

## 膨胀

In [108]:
img2 = cv2.imread(r"image\dilation.bmp",cv2.IMREAD_GRAYSCALE)

In [109]:
kernel = np.ones((3,3),dtype = np.uint8)

In [111]:
dst2  = cv2.dilate(img2,kernel,iterations = 3)

In [112]:
cv2.imshow("Medi",dst2)
cv2.imshow("img",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 开运算
###  先腐蚀再膨胀
开运算可以去除物体外部噪声

In [114]:
openling = cv2.imread(r"image\opening.bmp",cv2.IMREAD_GRAYSCALE)
openling.shape

(600, 800)

In [117]:
dst = cv2.morphologyEx(openling,cv2.MORPH_OPEN,kernel,iterations = 5)

In [118]:
cv2.imshow("Medi",dst)
cv2.imshow("img",openling)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 闭运算
###  先膨胀再腐蚀
闭运算可以去除物体内部噪声

In [131]:
closing = cv2.imread(r"image\closing.bmp",cv2.IMREAD_GRAYSCALE)

In [140]:
dst = cv2.morphologyEx(closing,cv2.MORPH_GRADIENT,kernel,iterations = 20)

In [141]:
cv2.imshow("Medi",dst)
cv2.imshow("img",openling)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 作业

In [203]:
cat = cv2.imread(r'image\kitty.jpg',cv2.IMREAD_GRAYSCALE)
catSRC = cv2.imread(r'image\kitty.jpg')
dog = cv2.imread(r'image\dog.jpg',cv2.IMREAD_GRAYSCALE)

In [193]:
threshCat,dstCat = cv2.threshold(cat,0,255,cv2.THRESH_BINARY_INV|cv2.THRESH_OTSU)
threshDog,dstDog = cv2.threshold(dog,0,255,cv2.THRESH_BINARY|cv2.THRESH_OTSU)

In [194]:
kernel = np.ones((2,2),dtype = np.uint8)

In [195]:
CatMorph = cv2.morphologyEx(dstCat,cv2.MORPH_OPEN,kernel,iterations = 5 )

In [167]:
cv2.imshow("cat",cat)
cv2.imshow("binary_invdstCat",CatMorph)

# cv2.imshow("dog",dog)
# cv2.imshow("binary_invdstDog",dstDog)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [168]:
CatMorph

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [171]:
(x,y) = CatMorph.shape

In [177]:
print(np.where(CatMorph==255))


(array([ 26,  26,  26, ..., 542, 542, 542], dtype=int64), array([196, 197, 198, ..., 354, 355, 356], dtype=int64))


In [196]:
minx = min(np.where(CatMorph==255)[0])
miny = min(np.where(CatMorph==255)[1])

In [182]:
miny

93

In [197]:
maxx = max(np.where(CatMorph==255)[0])
maxy = max(np.where(CatMorph==255)[1])

In [206]:
cv2.rectangle(catSRC,(miny,minx),(maxy,maxx),(0,0,255))

array([[[201, 226, 228],
        [200, 225, 227],
        [203, 226, 228],
        ...,
        [228, 228, 228],
        [254, 254, 254],
        [255, 255, 255]],

       [[198, 223, 225],
        [196, 221, 223],
        [196, 219, 221],
        ...,
        [228, 228, 228],
        [254, 254, 254],
        [255, 255, 255]],

       [[200, 223, 225],
        [196, 219, 221],
        [191, 214, 216],
        ...,
        [228, 228, 228],
        [254, 254, 254],
        [255, 255, 255]],

       ...,

       [[253, 254, 255],
        [253, 254, 255],
        [253, 254, 255],
        ...,
        [243, 243, 243],
        [255, 255, 255],
        [253, 253, 253]],

       [[250, 251, 255],
        [250, 251, 255],
        [250, 251, 255],
        ...,
        [253, 253, 253],
        [255, 255, 255],
        [253, 253, 253]],

       [[253, 254, 255],
        [253, 254, 255],
        [253, 254, 255],
        ...,
        [250, 250, 250],
        [247, 247, 247],
        [249, 249, 249]]

In [208]:
cv2.imshow("catSRC",catSRC)
cv2.imshow("binary_invdstCat",CatMorph)

# cv2.imshow("dog",dog)
# cv2.imshow("binary_invdstDog",dstDog)


cv2.waitKey(0)
cv2.destroyAllWindows()